### PR TITLE
[WIP]add something below all cards in column #332

### PR DESCRIPTION
**Pull request by anuradhabharti**
* [ ] Documentation

### CODE REVIEW

**Comment by Sabrinovsky** [comment]
@anuradhabharti this is still on developing? if yes, please put a [WIP] message so we can review when u done.

**Comment by anuradhabharti** [comment]
@Sabrinovsky I solved the issue but I didn't update the docs, test and add myself as a contributor.

**Comment by anuradhabharti** [comment]
@Sabrinovsky It's done.

**Comment by Sabrinovsky** [comment]
@anuradhabharti Thanks for your contribution, we really appreciate it.

About the PR, i think i should go for another approach. Looks like you just moved the card adder to the bottom of the column. I think the issue #332 is more like the Board user pass a component to render on the bottom of the column.

I imagine something like the [rendercolumnheader](https://github.com/lourenci/react-kanban#rendercolumnheader) that we have.

Something like this:
`<Board renderColumnFooter={() <footer />} />`
And then anything the user pass here, will be rendered on the column footer.

Want to try something like this?
I recommend you to work on the beta branch, it'll be release soon.


I think that a card adder on the column can be a good idea too, but we should let the user choose if he want it on the top, bottom or both.

**Comment by anuradhabharti** [comment]
Yes

**Comment by lourenci** [comment]
Hi, @anuradhabharti. We're getting this project back to the track. Are you working on this issue yet? Or I can close it? Thanks.

**Pull request closed without merging**
